#!/bin/sh

# Start keybind daemon (sxhkd)
pgrep -x sxhkd > /dev/null || sxhkd &

# Autostart

./autostart.sh &


# bspwm

bspc monitor -d 1 2 3 4 5

bspc config border_width         0
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox         desktop='1' state=floating
bspc rule -a firefox-nightly desktop='1' state=floating
bspc rule -a code-oss        desktop='2'
bspc rule -a spotify         desktop='3'
bspc rule -a discord         desktop='4'
