[general]
autosens = 1
bars = 20
framerate = 144
lower_cutoff_freq = 50

[input]
method = pipewire
source = auto
sample_rate = 48000

[eq]
1=1.5
2=1.5
3=1.5
4=1.5
5=1.5

[output]
method = raw
data_format = ascii
raw_target = /dev/stdout
bit_format = 16bit
channels = mono
ascii_max_range = 1000
